#Dont change unless you want to reset the config
ConfigVersion: 4
#Where should data be stored, this can be YAML, MySQL or SQLite.
#If it is MySQL you will need to fill in the database settings at the bottom of the config
DataStorage: YAML
#Downloads and installs updates when available
DownloadUpdates: true
#How many times can a player get their password wrong before the LoginAttemptsReachedCommand is run
LoginAttempts: 3
#Command to run after a player get their password wrong
LoginAttemptsReachedCommand: "kick %NAME% You got your password wrong %ATTEMPTS% times!"
#How long does a player have to be offline for before we make them login again (in minutes), they will always need to login again if their IP address changes
LogoutTimeout: 1
#This will stop players using their inventory while not logged in, this includes disallowing item pickup, drop and moving
InventoryLock: true
#This will hide the players inventory while they aren't logged in and give it back when they login
HideInventory: true
#After this number of days have passed, the players data (including password) will be removed, that means that the player will need to register again
PlayerTimeout: 365

#Database settings for if you wish to use a Database as your data store
Database:
  #The URL and port of your database
  location: "localhost:3306"
  username: "root"
  password: ""
  #This should be the name of a database on your database server
  dbName: "SpigotServer"